name: "Cachix Binary Cache"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/
    - uses: yaxitech/nix-install-pkgs-action@v3
      with:
        packages: "github:Mic92/nix-fast-build"
    - uses: cachix/cachix-action@v14
      with:
        name: 0x006e-nix
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix-fast-build --cachix-cache 0x006e-nix --skip-cached
