name: update-flake-lock
on:
  workflow_dispatch:
    inputs:
      bumpWhat:
        description: Which flake input? (leave blank for all)
        required: false
        type: string

  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00
  push:
      paths:
        - 'flake.nix'
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v29
        with:
          inputs: ${{ inputs.bumpWhat }}
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake packages
        uses: 0x006e/nix-update-action@1.1.1
        with:
          blacklist: "zoho-mail,windsurf,zen-browser-unwrapped"
          token: ${{ secrets.GITHUB_TOKEN }}
