name: update-flake-lock
on:
  workflow_dispatch:
    inputs:
      bumpWhat:
        description: Which flake input? (leave blank for all)
        required: false
        type: string

  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00
  push:
      paths:
        - 'flake.nix'
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Reformat *.nix files
        run:  nix fmt
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          inputs: ${{ inputs.bumpWhat }}
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
  updateFlakePackages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake packages
        uses: 0x006e/nix-update-action@1.1.1
        with:
          blacklist: "zoho-mail,windsurf"
